package com.pss.enums;

public enum State {
    INIT_SIMULATION,
    READ_FILE,
    PARSE_CONFIG,
    STORE_CONFIG,
    SIMULATION_INITIALIZED,
    START_SIMULATION,
    UPDATE_POSITION,
    INCREMENT_STEP_COUNTER,
    SIMULATION_COMPLETED,
    STORE_RESULTS,
    PREPARE_PLOT_DATA,
    SAVE_PLOT_AS_PNG,
    DISPLAY_PLOT_IN_GUI,
    PRINT_RESULTS_TO_CONSOLE,
    OUTPUT_RESULT
}
