package com.pss.enums;

public enum State {
    SIM_INITIALIZED,
    SIM_RUNNING,
    SIM_COMPLETE,
    SIM_OUTPUT_RESULT,
    T_SIM_INIT,
    T_READ_FILE,
    T_PARSE_CONFIG,
    T_STORE_CONFIG,
    T_START_SIM,
    T_UPDATE_POSITION,
    T_STORE_RESULTS,
    T_PREPARE_PLOT_DATA,
    T_DISPLAY_PLOT,
    T_PRINT_RESULTS_TO_CONSOLE
}
